# TODO: auto-generate this file
age-keys: &everyone # Master key
  - &bitwarden age10nwesuk0gr9nvfdcz3t4la6kp39cwrftn7z7chqyc4935gjjke7sa7hm7v

  # Host root keys
  - &bee age1y9exz75zcgjzcpzfjvj744sud2jwtxsy6u8r6u5tc7zlzx5y4aaqjvrw9j
  - &cuttlefish age18srdc3p7e7rd5quv7vsv2qxaysje2pnx22jvh0s5yf84vakm4gjsknygvy
  - &drywell age1hwlyzr0cqjjl9kv3ptseca99pnskguy8shgu8ujdpweyjhwh44zsu3sg0j
  - &pavil age1k7q7etwxmqdf59j47r58yyxx5ecjsjx9nkm8h4t4pggnd5arj9fqc4g23u
  - &rpi3 age189fhnxddwst08ug2j644nqd9vtxf2tp2kr3ygmutruayvzt7ss9sd3jf4m
  - &nib age1szk33dt0yyeru746p0elrym3hpc5hr6w6lqz0hd8xhrdt44k3sdqmpx0lk
  - &installer-test age185nwxyqzcghmdq5pjcad8aswgjmujd8pauet0urmum57uxx07ecs7dgt6g
  - &mallow age1h8cp3pwklm5tfcr5udxj7q8yfkfww368f0c4uymzfkzr5r5qpv4q82fkxy
  - &pixie age1zx9kfxfre3zyuazgr4wkrh0gqdudqj3e6gcuts3mr9ly8jkfmctsl9pqnk
  - &trident age1jgc4n5klps48l83gmw7mqmh0x45ss3uvmpe8muys8ag90sf84arqqymclg
  - &wyse age12e02a0j3k2wy4h6sllynytej0zlvmu5w0ky78gtzlk005gf2pu5sv08l35

creation_rules:
  #######################
  ##### Shared keys #####
  #######################

  - path_regex: ^system/(.*/)?secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age: *everyone

  #####################
  ##### Host keys #####
  #####################

  - path_regex: ^hosts/bee/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *bee
          - *pavil

  - path_regex: ^hosts/cuttlefish/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *cuttlefish

  - path_regex: ^hosts/drywell/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *drywell

  - path_regex: ^hosts/pavil/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *pavil

  - path_regex: ^hosts/rpi3/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *rpi3

  - path_regex: ^hosts/nib/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *nib

  - path_regex: ^hosts/installer-test/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *installer-test

  - path_regex: ^hosts/mallow/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *mallow

  - path_regex: ^hosts/pixie/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden
          - *pixie

  - path_regex: ^hosts/bitwarden/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
      - age:
          - *bitwarden

  - path_regex: ^hosts/trident/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
    - age:
      - *bitwarden
      - *trident

  - path_regex: ^hosts/wyse/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
    - age:
      - *bitwarden
      - *wyse
