age-keys: &age-keys
  # Master key
  - &bitwarden age10nwesuk0gr9nvfdcz3t4la6kp39cwrftn7z7chqyc4935gjjke7sa7hm7v

  # Host root keys
  - &ace age1uzs99xpmkp6kafjumk8zpjjhxg47ytzpgyuxts3jh7mgayj0dans8agyu6
  - &cuttlefish age18srdc3p7e7rd5quv7vsv2qxaysje2pnx22jvh0s5yf84vakm4gjsknygvy
  - &drywell age1hwlyzr0cqjjl9kv3ptseca99pnskguy8shgu8ujdpweyjhwh44zsu3sg0j
  - &nebula age1rl8fffzc62gkxdut5dvc2gs7ljksx96cm09kusy0xvcjzxxng5aqt29wca
  - &pavil age1k7q7etwxmqdf59j47r58yyxx5ecjsjx9nkm8h4t4pggnd5arj9fqc4g23u
  - &portable age1gcjvff6wd48as5jmym0d9efalye248vmmwe6r2htz2wgv6xyldpqjjrlqu
  - &installer age1na853jz9pslss7rleap2hwgaxmlrjrry8yh2rjrn90tcee4r5f3ssjj5vp
  - &rpi3 age189fhnxddwst08ug2j644nqd9vtxf2tp2kr3ygmutruayvzt7ss9sd3jf4m
  - &limb-1 age1egxva7myft04uzkfurq4altj92neuchtggw62z55p3tt3ddlnvxsf6ersm
  - &nib age1szk33dt0yyeru746p0elrym3hpc5hr6w6lqz0hd8xhrdt44k3sdqmpx0lk
  - &installer-test age185nwxyqzcghmdq5pjcad8aswgjmujd8pauet0urmum57uxx07ecs7dgt6g
  - &mallow age1u20gs4lje4skk96xc4uftxdcvudd39c6c3y7ag4mu4qclwh6ny2qecjlaj

creation_rules:
  #######################
  ##### Shared keys #####
  #######################

  - path_regex: ^sys/secrets/age-keys.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age:
      - *bitwarden

  - path_regex: ^sys/secrets/shared.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age: *age-keys

  #####################
  ##### Host keys #####
  #####################

  - path_regex: ^hosts/ace/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *ace

  - path_regex: ^hosts/cuttlefish/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *cuttlefish

  - path_regex: ^hosts/drywell/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *drywell

  - path_regex: ^hosts/nebula/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *nebula

  - path_regex: ^hosts/pavil/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *pavil

  - path_regex: ^hosts/portable/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *portable

  - path_regex: ^hosts/rpi3/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *rpi3

  - path_regex: ^hosts/limb-1/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *limb-1

  - path_regex: ^hosts/nib/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *nib

  - path_regex: install.secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *pavil

  - path_regex: ^hosts/installer-test/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *installer-test

  - path_regex: ^hosts/mallow/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *mallow

  - path_regex: ^hosts/mallow/install.secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *mallow
      - *pavil
