# TODO: auto-generate this file

age-keys: &everyone
  # Master key
  - &bitwarden age10nwesuk0gr9nvfdcz3t4la6kp39cwrftn7z7chqyc4935gjjke7sa7hm7v

  # Host root keys
  - &cuttlefish age18srdc3p7e7rd5quv7vsv2qxaysje2pnx22jvh0s5yf84vakm4gjsknygvy
  - &drywell age1hwlyzr0cqjjl9kv3ptseca99pnskguy8shgu8ujdpweyjhwh44zsu3sg0j
  - &pavil age1k7q7etwxmqdf59j47r58yyxx5ecjsjx9nkm8h4t4pggnd5arj9fqc4g23u
  - &rpi3 age189fhnxddwst08ug2j644nqd9vtxf2tp2kr3ygmutruayvzt7ss9sd3jf4m
  - &nib age1szk33dt0yyeru746p0elrym3hpc5hr6w6lqz0hd8xhrdt44k3sdqmpx0lk
  - &installer-test age185nwxyqzcghmdq5pjcad8aswgjmujd8pauet0urmum57uxx07ecs7dgt6g
  - &mallow age1u20gs4lje4skk96xc4uftxdcvudd39c6c3y7ag4mu4qclwh6ny2qecjlaj

creation_rules:
  #######################
  ##### Shared keys #####
  #######################

  - path_regex: ^sys/secrets/age-keys.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age:
      - *bitwarden

  - path_regex: ^sys/secrets/shared.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age: *everyone

  - path_regex: ^system/nixos/networking/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age: *everyone

  #####################
  ##### Host keys #####
  #####################

  - path_regex: ^hosts/cuttlefish/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *cuttlefish

  - path_regex: ^hosts/drywell/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *drywell

  - path_regex: ^hosts/pavil/secrets.yaml$
    unencrypted_regex: ^(exports|enable|sopsNix)$
    key_groups:
    - age:
      - *bitwarden
      - *pavil

  - path_regex: ^hosts/rpi3/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *rpi3

  - path_regex: ^hosts/nib/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *nib

  - path_regex: install.secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *pavil

  - path_regex: ^hosts/installer-test/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *installer-test

  - path_regex: ^hosts/mallow/secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *mallow

  - path_regex: ^hosts/mallow/install.secrets.yaml$
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *mallow
      - *pavil
