services:
  cloudsql-proxy:
    container_name: cloudsql-proxy

    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy

    volumes:
      - "${CSQL_PROXY_CREDENTIALS_FILE}:${CSQL_PROXY_CREDENTIALS_FILE}"

    env_file: .env

    ports:
      - 5432:5432

    restart: unless-stopped
