version: "3.9"
services:
  steam:
    image: steam:latest
    ports:
      - 8080:8080
      - 5900:5900
    environment:
      LD_LIBRARY_PATH: /run/opengl-driver/lib/
    volumes:
      - /run/opengl-driver:/run/opengl-driver
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd

      # - /dev/dri/card0:/dev/dri/card0
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/drm_dp_aux0:/dev/drm_dp_aux0
      # - /dev/drm_dp_aux1:/dev/drm_dp_aux1
    entrypoint: sway
