version: "3.9"
services:
  steam:
    image: steam:latest
    ports:
      - 8080:8080
      - 5900:5900
    environment:
      LD_LIBRARY_PATH: /run/opengl-driver/lib/
      WLR_BACKENDS: drm
      WLR_LIBINPUT_NO_DEVICES: "1"
    volumes:
      - /run/opengl-driver:/run/opengl-driver
      - ./home:/home/steam
    devices:
      - /dev:/dev
      #- /dev/dri:/dev/dri
      #- /dev/tty0:/dev/tty0

      #- /dev/nvidia0:/dev/nvidia0
      #- /dev/nvidiactl:/dev/nvidiactl
      #- /dev/nvidia-uvm:/dev/nvidia-uvm
      #- /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      #- /dev/nvidia-modeset:/dev/nvidia-modeset
      #- /dev/fb0:/dev/fb0

      #- /dev/kfd:/dev/kfd
      # - /dev/dri/card0:/dev/dri/card0
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/drm_dp_aux0:/dev/drm_dp_aux0
      # - /dev/drm_dp_aux1:/dev/drm_dp_aux1
    #entrypoint: sway --unsupported-gpu
    entrypoint: sh
    privileged: true
    tmpfs:
      - /tmp
