age keys:
  # Master key
  - &bitwarden age10nwesuk0gr9nvfdcz3t4la6kp39cwrftn7z7chqyc4935gjjke7sa7hm7v

  # Host root keys
  - &ace age1uzs99xpmkp6kafjumk8zpjjhxg47ytzpgyuxts3jh7mgayj0dans8agyu6
  - &cuttlefish age18srdc3p7e7rd5quv7vsv2qxaysje2pnx22jvh0s5yf84vakm4gjsknygvy
  - &nebula age1rl8fffzc62gkxdut5dvc2gs7ljksx96cm09kusy0xvcjzxxng5aqt29wca
  - &pavil age1k7q7etwxmqdf59j47r58yyxx5ecjsjx9nkm8h4t4pggnd5arj9fqc4g23u

creation_rules:
  #######################
  ##### Shared keys #####
  #######################

  - path_regex: secrets/age-keys.yaml
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age:
      - *bitwarden

  - path_regex: secrets/shared.yaml
    unencrypted_regex: ^(meta|.*_unencrypted)$
    key_groups:
    - age:
      - *bitwarden
      - *pavil
      - *ace
      - *nebula
      - *cuttlefish

  #####################
  ##### Host keys #####
  #####################

  - path_regex: secrets/hosts/ace.yaml
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *ace

  - path_regex: secrets/hosts/cuttlefish.yaml
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *cuttlefish

  - path_regex: secrets/hosts/nebula.yaml
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *nebula

  - path_regex: secrets/hosts/pavil.yaml
    unencrypted_regex: ^(meta|.*_unencrypted|.*\.pub)$
    key_groups:
    - age:
      - *bitwarden
      - *pavil
